### ISSUE TITLE
A request on adding my paper

### ISSUE THREAD

**Issue by maestrojeong** [matthewvowels1/Awesome-VAEs#1]
My paper on disentanglement based on VAE fraemwork was accepted in ICML2019.
Here is the link [http://proceedings.mlr.press/v97/jeong19d.html](http://proceedings.mlr.press/v97/jeong19d.html)
My method achieved state of the art performance on disentanglement task.

Would you consider this??

Thank you!

**Comment by matthewvowels1** [comment]
Firstly, congratulations on the acceptance.

Secondly, I will definitely include your paper with the next push! This is a very exciting topic and I am looking forward to reading your paper.

Best wishes for your continuing and future research.
