### ISSUE TITLE
Typo on page 3.

### ISSUE THREAD

**Issue by erow** [matthewvowels1/Awesome-VAEs#3]
This list is awesome! However, I believe there are some mistakes there.
The definition of mutual information on page 3:
![image](https://user-images.githubusercontent.com/7524356/102009258-28cc2b80-3d71-11eb-87d9-8fa882eeed61.png)
should be  $H_p(z) - H_p(z|x)$ , and you missed log here.

**Comment by matthewvowels1** [comment]
Thanks for checking out the list and for your kind words!  

And great spot, thanks! That's quite a blunder. Should be fixed now.

**Comment by erow** [comment]
You are welcome. I am curious about which area do you focus on?

**Comment by matthewvowels1** [comment]
Currently working on latent variable models for causal discovery : ] how about yourself?

**Comment by erow** [comment]
My work is about disentanglement mainly based on VAEs. Your work is interesting because independence is sufficient to support disentanglement.
