### ISSUE TITLE
The sourse of the ppt

### ISSUE THREAD

**Issue by XM-WANG** [matthewvowels1/Awesome-VAEs#4]
Thanks for your sharing! I am quite interested in the PPT in the repository and I wanna know if there is a presentation (video) about the PPT?

**Comment by matthewvowels1** [comment]
Thank you for your support!

There is a video which is currently being edited. We haven't decided whether to release it publicly yet, but if we do, I'll be sure to add it to this repository, and add a comment to this issue : ]

Thanks again!

**Comment by XM-WANG** [comment]
Thanks!

**Comment by sangyun884** [comment]
@matthewvowels1 Did you release the video? The slide seems extremely interesting.
